### ISSUE TITLE
Determine efficient way to parse and remove comments in DAX

### ISSUE THREAD

**Issue by teasot** [teasot/tom2amo#2]
DAX has three comment types:

1. "--" line comment
2. "//" line comment
3. "/* ... */" block comments.

Now, when parsing a command, we need to remove all comments before parsing the command.

I need to add functionality to further strip --, and ensure that if -- is placed before /* , that it is not treated as a block comment (the link below handles only // and /*):

[https://stackoverflow.com/questions/3524317/regex-to-strip-line-comments-from-c-sharp/3524689#3524689](https://stackoverflow.com/questions/3524317/regex-to-strip-line-comments-from-c-sharp/3524689#3524689)

**Comment by teasot** [comment]
Please note this means I will NOT be supporting comments in 1103... sorry!

**Comment by otykier** [comment]
We can use the existing DAXLexer.cs class in Tabular Editor to strip comments from DAX expressions. Would that help?

**Comment by teasot** [comment]
Hmm... will look into this. I managed to get an _awful_ hand rolled parser running, but it is quite bulky.
I might stick to my bulky solution for now, simply because I understand it far better than the Antlr code.

**Comment by teasot** [comment]
Perhaps, I should simply assume the user is "playing nice".

Simply finding any instances of "CREATE MEASURE 'Table'[Measure]=..." should be enough to satisfy most cases, specifically including VS. As long as we read and write the files consistently, it will save a LOT of code and worrying.

I can add it to the backlog, but realistically this issue should not come up often.

**Comment by teasot** [comment]
Tagged as long-term: this is one of those issues where I will spend days perfecting it, for a case that will only occur in extraordinary cases.

**Comment by teasot** [comment]
I have currently got a basic "parser" working, that can determine if a string is in a "table", "string", or "measure" name, allowing me to pick up key words. As a result, I am keeping this open for my own tracking, then closing it once my "parser" is complete.

**Comment by teasot** [comment]
Closing, as parser effectively complete enough to know it can be expanded to KPIs. KPI parsing will be relatively simple using this method, though work still needs to be done.
